name: Package Persepolis DM for windows x64 with Nuitka
on: workflow_dispatch

jobs:
  bundle-windows:
    runs-on: windows-latest
    steps:
      - name: Get persepolis
        uses: actions/checkout@v4
        with:
          repository: persepolisdm/persepolis
          path: persepolis

      - name: Get build assets
        uses: actions/checkout@v4
        with:
          repository: persepolisdm/persepolis-windows-package-build
          path: persepolis-windows-package-build

      - name: Install requirements
        run: |
          pip install PySide6 requests pypiwin32 setproctitle psutil yt_dlp urllib3 pysocks nuitka ordered-set zstandard

      - name: Download ffmpeg
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "yt-dlp/FFmpeg-Builds"
          latest: true
          fileName: "ffmpeg-master-latest-win64-gpl.zip"

      - name: Install MSVC build tools
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build PersepolisBI
        run: |
          call cd persepolis
          call python -m nuitka --standalone --onefile --enable-plugin=pyside6 --msvc=latest --low-memory --windows-icon-from-ico=..\persepolis-windows-package-build\persepolis2.ico --output-filename="PersepolisBI.exe" resources\PersepolisBI.py
        shell: cmd

      - name: Build Persepolis Download Manager
        run: |
          call cd persepolis
          call python -m nuitka --standalone --onefile --enable-plugin=pyside6 --msvc=latest --low-memory --windows-icon-from-ico=..\persepolis-windows-package-build\persepolis1.ico --windows-console-mode=disable --output-filename="Persepolis Download Manager.exe" "persepolis\Persepolis Download Manager.py"
        shell: cmd

      - name: Move executables to dist
        run: |
          mkdir persepolis\dist
          move persepolis\PersepolisBI.exe persepolis\dist\
          move "persepolis\Persepolis Download Manager.exe" persepolis\dist\
        shell: cmd

      - name: Extract ffmpeg
        run: 7z e ffmpeg-master-latest-win64-gpl.zip -o'.\persepolis\dist' ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe

      - name: Build Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: persepolis-windows-package-build\setupX64.iss
          options: /O+

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: Archive build
          path: .\persepolis-windows-package-build\Output\
